-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/Lucas-C/pre-commit-hooks-html
    sha: v1.2.1
    hooks:
    -   id: validate-html
-   repo: git://github.com/pre-commit/mirrors-ruby-lint
    sha: 'v2.3.1'
    hooks:
    -   id: ruby-lint
